### ISSUE TITLE
Question about one assumption in the paper

### ISSUE THREAD

**Issue by chenxi-yang** [tuomaso/radial_rl_v2#4]
Hi,

In your paper,  you mentioned 'For our continuous control experiments, the output of our policy are the parameters µ, Σ of a Gaussian, with covariance being diagonal and independent of input state s.' May I ask why the Σ is independent of input state s? Σ also comes out from the neural network using s as the only input, why would a slight change of s not influence Σ?

Thank you!

**Comment by tuomaso** [comment]
Thanks for the question,

This was done for practical reasons as we found having a standard deviation independent of state helped improve training stability and overall performance. Ideally it would be a function of s but this is currently hard to learn. You can see the in [CstPolicy class](https://github.com/tuomaso/radial_rl_v2/blob/6490ef9f71fd22a859a864e3d42a8b597c7e5908/MuJoCo/src/policy_gradients/models.py#L651) used for our training the standard deviation is not an output of the neural net but an independent learnable parameter.
